[[plugins]]
package = "@netlify/plugin-gatsby"

[[redirects]]
  from = "/zoom"
  to = "https://pitt.zoom.us/my/pittcsc"
  status = 200
  force = true

[[redirects]]
  from = "/blog"
  to = "https://pittcsc-blog.netlify.app"
  status = 200
  force = true