name: Gatsby Publish

on:
  push:
    branches: [master]
  schedule:
    - cron: "0 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GATSBY_NOTION_TOKEN: "secret_pYfqoNgRHJtgRzhXo8Wo4JwRNYEgaQTlzcARLDIL5wh"
      GATSBY_NOTION_DATABASE_ID: "f669dd3a-4816-4010-b4aa-422e86472f0f"
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
