name: Trigger Netlify Build
on:
  schedule:
    # Run every day at midnight
    - cron: '0 */3 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/6102d1cee677dd37bbfd8578